/**************************************************************************************
Apex Class Name    : Constant
Version            : 1.0
Created Date       : June 06 2017
Function           :This is used for defining the constants.
Modification Log   :
------------------------------------------------------------------------------
 * Developer                   Date                   Description
 * ----------------------------------------------------------------------------
 * Suresh S                  06/06/2017              Original Version
*******************************************************************************/
public with sharing class Constant {
    //move this things to Labels
    public static final String EDIT= 'EDIT';
    public static final String STATUS_QUALIFIED= 'Qualified';
    public static final String MERGE_REASON_MANUALLY= 'Manually Merged';
    public static final String Has_Booking= 'Has Booking';
    public static final String triton_id= 'triton id';
    public static final String Decision= 'decision';
    public static final String stringTrue = 'True';
    public static final String stringFalse = 'False';
    public static final String stringPlus = '+';
    public static final String stringNA = 'NA';
    public static final String stringOne= '1';
    public static final String stringZero= '0';
    public static final String blank= '';
    public static final string TBC = 'TBC';
    public static final String stringLead= 'Lead';
    public static final String stringAccount= 'Account';
    public static final String ACCOUNT_PREFIX= '001P';
    public static final String LEAD_PREFIX= '00Q';
    public static final String LEADSTAGEWON ='Closed Won';
    public static final String LEADSTAGEFOLLOWUP='FollowUp';
    public static final String LEADSTAGETBC = 'TBC';
    public static final String LEAD_STAGE_QUALIFIED = 'Qualified';
    public static final String Opp_STAGE_Closed = 'Closed';
    public static final String Opp_STAGE_Inactive = 'InActive';
    public static final String Opp_STAGE_ClosedLost = 'Closed Lost';
    public static final String Opp_STAGE_Won = 'Won';
    public static final String Opp_STAGE_BKN = 'BKN';
    public static final string Opp_Stage_RES = 'RES';
    public static final string space = ' ';
    public static final String alphabetV ='V';
    public static final String semiColon=';';
    public static final String underScore = '_';
    public static final String CAM = 'CAM';
    public static final String LEAD_STAGE_CONVERTED = 'Converted';
    public static final String HOMEPHONE = 'Home Phone';
    public static final String OTHERPHONE = 'Other Phone';
    public static final String MOBILEPHONE = 'Mobile Phone';
    public static final String SEARCH = 'search';
    public static final String SEARCH_DEL = 'search-del';
    public static final string Closed_Lost = 'Closed Lost';
    public static final string Sent= 'Sent';
    public static final string Responded= 'Responded';
    public static final string Invited= 'Invited';
    public static final string Attended= 'Attended';
    public static final String MERGEORCONVERTED = 'MergeOrConvert';
    public static final String EMAILONEFIELD = 'Email';
    public static final String EMAILSECONDFIELD = 'Email2';








}